### ISSUE TITLE
What is the `electron-port` folder doing?

### ISSUE THREAD

**Issue by eamonburns** [Nikhil-Software-Cartel/TerminalProfileManager#3]
I deleted the entire thing and the app seems to be working fine. Is it doing something I can't see? Is it even necessary?

**Comment by nikhil-swamix** [comment]
hi @Agent-E11 , it core intention behind electron-port was to implement the functionality in nodejs, which offers similar functionality to pywebview, however the standalone application build was taking 60MB at minimum which was later discontinued. it just exists as a part of RnD, no strings attached. we can dispose it. should it be required in future i will create a seperate repo. as of now pywebview does the job and is very flexible. and if python is installed (which i believe is popular than node) in many pc it can be directly run from source using launcher.pyw , which has lower startup time and cleaner approach.
hence we can delete the folder.

**Comment by eamonburns** [comment]
Good to know
